### ISSUE TITLE
Export a SysfsGpioError type

### ISSUE THREAD

**Issue by jwilm** [posborne/rust-sysfs-gpio#7]
The public API for this crate currently returns `Result<_, std::error::Error>`. This makes composing errors from this crate into a higher level error type difficult since we can not use the usual `std::convert::From` and `try!` idioms.

I propose a `SysfsGpioError` type is added and returned as the Error type for methods returning a Result. Not having though about it much yet, it might look something like this.

```rust
// Assuming these are all wrapping a lower level error of some sort, otherwise they
// could just take a string or nothing (add description in the Error impl).

#[derive(Debug)]
pub enum SysfsGpioError {
    SetDirection(Error),
    SetValue(Error),
    Export(Error),
    Unexport(Error),
    // etc
}
```

And then consumers can easily `impl From<SysfsGpioError>` for their error type.

Assuming this is something you're interested in, and that you don't get to it first, I'll put a PR up soon.

Thanks!

**Comment by posborne** [comment]
Good thinking.  I agree that things can be much better than what is currently present.  I have actually started to figure out if it makes sense to define a generic trait and set of errors for a GPIO abstraction that can be shared across projects (e.g. implemented by this lib for Linux but also usable in something like zinc.rs).  In that case, we would probably be hiding a bit more information (especially on errors) but that is probably worth it for the methods covered by the trait.

Here's what I have so far: https://github.com/posborne/rust-gpio/pull/1.  I would love additional feedback.

With that in mind, I don't want that to hold up any improvements that could be made here.  There is a lot of limitations with `no_std`, so I think that even if the trait is implemented eventually, we will want to layer that impl on top of a set of methods similar to what exists today.

With the snippet you provided, I'm not 100% convinced the close match to the individual methods makes sense, but I'm not sure of a good alternative right now.

**Comment by jwilm** [comment]
I ended up coming to the same conclusion about error variants. There is a PR (#8) up which contains the changes I proposed. Looking forward to your feedback.

The idea for generic GPIO traits is great, and I would be happy to look at posborne/rust-gpio#1. `#[no_std]` is something I've thought about a little but not enough to be aware of all the issues.

**Comment by posborne** [comment]
Yeah, `#[no_std]` is tricky.  I'm waiting until some of the core stabilization fallout finished up before going after that space too aggressively: https://github.com/rust-lang/rust/issues/27701
